owner: thinkintegrated-web
repo: upptime

sites:
  - name: bhpcchamber.org
    url: https://www.bhpchamber.org
  - name: blacktipit.com
    url: https://www.blacktipit.com
  - name: ciaimaging.com
    url: https://www.ciaimaging.com
  - name: confettiandcreativity.com
    url: https://www.confettiandcreativity.com
  - name: congdonyards.com
    url: https://www.congdonyards.com
  - name: crittercontroldallas.com
    url: https://www.crittercontroldallas.com
  - name: cshpinnovation.com
    url: https://www.cshpinnovation.com
  - name: destinyfamilyoffice.com
    url: https://www.destinyfamilyoffice.com
  - name: eventsatcongdonyards.com
    url: https://www.eventsatcongdonyards.com
  - name: integralandcompany.com
    url: https://www.integralandcompany.com
  - name: invernessmedicalimaging.com
    url: https://www.invernessmedicalimaging.com
  - name: jobspartnership.org
    url: https://www.jobspartnership.org
  - name: matthiaspw.com
    url: https://www.matthiaspw.com
  - name: nicholswealth.com
    url: https://www.nicholswealth.com
  - name: orangeparkimaging.com
    url: https://www.orangeparkimaging.com
  - name: orlandoballet.org
    url: https://www.orlandoballet.org
  - name: srsradiology.com
    url: https://www.srsradiology.com
  - name: starterstudio.org
    url: https://www.starterstudio.org
  - name: cableelectrical.com
    url: https://www.cableelectrical.com
  - name: unlimitedwelding.com
    url: https://www.unlimitedwelding.com

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** - Client Uptime Monitoring"
  introMessage: Monitoring uptime and performance for our client websites.

# Notifications and advanced config can go below if needed
