name: Setup CI

on:
  push:
    paths:
      - '.upptimerc.yml'

jobs:
  setup:
    name: Setup Uptime
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install -g upptime@latest

      - name: Run Upptime Setup
        run: upptime setup
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
